name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ vnext ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.config'
      - '**/*.ini'

jobs:
  Windows:
    runs-on: windows-2022

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
 
    - name: Configure
      run: cmake -S ${{github.workspace}}/ -B ${{github.workspace}}/build -DNC_BUILD_TESTS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config "Release"

    - name: Run Tests
      run: ./nc-tools_tests test/collateral/input.txt

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nc-tools
        path: |
          ${{github.workspace}}/nc-tools.exe
          ${{github.workspace}}/assimp-vs143-mt.dll