name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.config'
      - '**/*.ini'

jobs:
  Windows:
    runs-on: windows-2022

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
 
    - name: Configure
      run: cmake -S ${{github.workspace}}/ -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config "Release"

    - name: Run Tests
      run: ./nc-tools_tests test/collateral/input.txt

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Test Release"
        files: |
          nc-tools.exe
          assimp-vc143-mt.dll
