name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ vnext ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.config'
      - '**/*.ini'

env:
  VERSION: '0.1.0'

jobs:
  Windows:
    runs-on: windows-2022

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
 
    - name: Configure
      run: cmake -S ${{github.workspace}}/ -B ${{github.workspace}}/build -DNC_BUILD_TESTS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config "Release"

    - name: Run Tests
      run: ./nc-tools_tests test/collateral/input.txt

    # - name: Create Artifacts
    # - uses: papeloto/action-zip@v1
    #   with:
    #     files: nc-tools.exe assimp-vc143-mt.dll
    #     dest: nc-tools.zip

    - name: Create Archive
      run: 7z a -tzip -mx=9 nc-tools.zip ./nc-tools.exe ./assimp-vc143-mt.dll

    - name: Publish to Artifactory
      run: curl -u ${{secrets.JFROG_USER}}:${{secrets.JFROG_PASSWORD}} -T ${{github.workspace}}/nc-tools.zip ${{format('https://ncstudios.jfrog.io/artifactory/nctools/{0}/nc-tools.zip', VERSION)}}