name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ vnext ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.config'
      - '**/*.ini'

jobs:
  Windows:
    runs-on: windows-2022

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
 
    - name: Configure
      run: cmake -S ${{github.workspace}}/ -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config "Release"

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: nc-tools
        path: ${{github.workspace}}/Release/NcAssetBuilder.exe
