name: Publish

on:
  workflow_dispatch:
  pull_request:
    branches: [ release ]
    types:
      - closed

env:
  VERSION: '0.1.1'

jobs:
  Publish:
    if: github.event.pull_request.merged == true
    runs-on: windows-2022

    steps:
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success
        pr: ${{github.event.pull_request.number}}
        name: nc-tools

    - name: Create Archive
      run: 7z a -tzip -mx=9 nc-tools.zip ./nc-tools.exe ./assimp-vc143-mt.dll

    - name: Publish to Artifactory
      run: curl -u ${{secrets.JFROG_USER}}:${{secrets.JFROG_PASSWORD}} -T ${{github.workspace}}/nc-tools.zip ${{ format('https://ncstudios.jfrog.io/artifactory/nctools/{0}/nc-tools.zip', env.VERSION) }}