name: Publish

on:
  workflow_dispatch:
  pull_request:
    branches: [ vnext, release ]
    types:
      - closed

env:
  VERSION: '0.1.0'

jobs:
  Publish:
    if: github.event.pull_request.merged == true
    runs-on: windows-2022

    steps:
    # - name: Get Artifacts
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: nc-tools

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success
        branch: vnext
        name: nc-tools
# Optional, directory where to extract artifact(s), defaults to current directory
# path: extract_here
# default false, just try to download from the last one
# check_artifacts:  false
# Optional, search for the last workflow run whose stored an artifact named as in `name` input
# default false
# search_artifacts: false

    - name: Publish to Artifactory
      run: curl -u ${{secrets.JFROG_USER}}:${{secrets.JFROG_PASSWORD}} -T ${{github.workspace}}/nc-tools.zip ${{ format('https://ncstudios.jfrog.io/artifactory/nctools/{0}/nc-tools.zip', env.VERSION) }}