name: Publish

on:
  workflow_dispatch:
  pull_request:
    branches: [ release ]
    types:
      - closed

env:
  VERSION: '0.1.1'

jobs:
  Publish:
    if: github.event.pull_request.merged == true
    runs-on: windows-2022

    steps:
    - name: Get Artifacts
      uses: actions/download-artifact@v3
      with:
        name: nc-tools

    - name: Publish to Artifactory
      run: curl -u ${{secrets.JFROG_USER}}:${{secrets.JFROG_PASSWORD}} -T ${{github.workspace}}/nc-tools.zip ${{ format('https://ncstudios.jfrog.io/artifactory/nctools/{0}/nc-tools.zip', env.VERSION) }}