name: Release

on:
  workflow_dispatch:

env:
  VERSION: '0.1.1'

jobs:
  Windows:
    runs-on: windows-2022

    steps:
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success
        branch: release
        name: nc-tools
        path: ${{github.workspace}}/artifacts

    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        prerelease: false
        automatic_release_tag: ${{format('v{0}', env.VERSION)}}
        files: |
          ${{github.workspace}}/artifacts/nc-tools.exe
