name: Release

on:
  workflow_dispatch:
    inputs:
      createRelease:
        required: true
        type: boolean

env:
  VERSION: '0.1.1'

jobs:
  Publish:
    runs-on: windows-2022

    steps:
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success
        branch: release
        name: nc-tools
        path: ${{ github.workspace }}\artifacts
        skip_unpack: true

    - name: Create release
      uses: softprops/action-gh-release@v1
      if: ${{ inputs.createRelease || github.ref == "refs/heads/release" }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ format('v{0}', env.VERSION) }}
        fail_on_unmatched_files: true
        files: ${{ github.workspace }}\artifacts\nc-tools.zip
